// Official site for each AI tool's category, shown as a "바로가기" link.
// AI 트렌드 has no single tool, so it's intentionally absent.
export const TOOL_SITE_URLS: Record<string, string> = {
  chatgpt: "https://chat.openai.com",
  claude: "https://claude.ai",
  gemini: "https://gemini.google.com",
  perplexity: "https://www.perplexity.ai",
  wrtn: "https://wrtn.ai",
  canva: "https://www.canva.com",
  midjourney: "https://www.midjourney.com",
  runway: "https://runwayml.com",
  higgsfield: "https://higgsfield.ai",
  seedance: "https://dreamina.capcut.com/seedance",
  kling: "https://klingai.com",
  capcut: "https://www.capcut.com",
  vrew: "https://vrew.voyagerx.com",
  suno: "https://suno.com",
  elevenlabs: "https://elevenlabs.io",
  heygen: "https://www.heygen.com",
  "notion-ai": "https://www.notion.com/product/ai",
  figma: "https://www.figma.com",
  cursor: "https://www.cursor.com",
  gamma: "https://gamma.app",
  notebooklm: "https://notebooklm.google",
  "clova-x": "https://clova-x.naver.com",
  "github-copilot": "https://github.com/features/copilot",
  copilot: "https://copilot.microsoft.com",
  lovable: "https://lovable.dev",
  "adobe-firefly": "https://firefly.adobe.com",
  veo: "https://deepmind.google/technologies/veo",
  typecast: "https://typecast.ai",
  grok: "https://grok.com",
  genspark: "https://www.genspark.ai",
  deepseek: "https://www.deepseek.com",
};
